image: exozet/php-fpm:7.3-sudo

cache:
  paths:
    - bin/
    - vendor/

stages:
  - test-backend

variables:
  DATABASE_HOST: mysql
  DATABASE_PORT: 3306
  MYSQL_ROOT_PASSWORD: root
  MYSQL_USER: db-user
  MYSQL_DATABASE: db-name
  MYSQL_PASSWORD: db-password
  MYSQL_ALLOW_EMPTY_PASSWORD: "1"
  PHP_MEMORY_LIMIT: "1024M"
  PHP_DATE_TIMEZONE: "Europe/Berlin"
  SYMFONY_DEPRECATIONS_HELPER: weak
  SYMFONY_ENV: test

lint-backend:
  stage: test-backend
  image: exozet/php-fpm:7.3.0-sudo
  tags:
    - docker
  script:
    - composer global require hirak/prestissimo
    - make install
    - make lint
  artifacts:
    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    expire_in: 1 day
    untracked: true

phpunit:
  stage: test-backend
  image: exozet/php-fpm:7.3.0-sudo
  tags:
    - docker
  script:
    - composer global require hirak/prestissimo
    - make install
    - php bin/phpunit --process-isolation --log-junit build/junit-reports/phpunit.xml
  artifacts:
    expire_in: 1 week
    reports:
      junit:
        - build/junit-reports/phpunit.xml
